model:
  mode: ['3din','3din'] #[encoder,depth,posecnn]
  framework: 'sfmlearner' #rebuild #sfmlearner
  load_paths:
    encoder: null #'/home/roit/models/torchvision/official/resnet18-5c106cde.pth'
    depth: null
    #pose: null
    posecnn: null
  device: 'cuda'
  scales: [0,1,2,3]
  lr: 0.0001
  scheduler_step_size: 15
  optimizer_path: null

dataset:
  type: 'kitti'
  path: '/home/roit/datasets/kitti'
  split:
    path: '/home/roit/datasets/splits/kitti/eigen_zhou_std'
    train_file: 'train.txt'
    val_file: 'val.txt'
  num_workers: 12
  batch_size: 8
  to_height: 192 #same with feed height
  to_width: 640
  full_width: 1242
  full_height: 375

feed_width: 640  #"'width' must be a multiple of 32"
feed_height: 192 #"'height' must be a multiple of 32"

scales: [0,1,2,3]
disparity_smoothness: 0.1 #set manual
cuda: True
device: 'cuda'

frame_sides: [-1,0,1]

yaml_file: /home/roit/aws/aprojects/DeepSfMLearner/opts/mc.yaml
log_dir: '/home/roit/models/DeepSfM/mc'
tb_log_frequency: 12
epoch: 20
model_first_save: 15
weights_save_frequency: 1
min_depth: 0.1
max_depth: 80.0