frame_sides: [-1,0,1]
#frame_sides: [0]
model:
  mode: "3din" #[encoder,depth,posecnn]
#  mode: "1in"
  load_paths:
    encoder: '/home/roit/models/DeepSfM/kitti/0324_2244/models/weights_19/encoder.pth'#1in
#    encoder: '/home/roit/models/DeepSfM/kitti/0323_2159/models/weights_19/encoder.pth'#3din
    #    encoder: '/home/roit/models/monodepth2_official/mono_640x192/encoder.pth'
    depth: '/home/roit/models/DeepSfM/kitti/0324_2244/models/weights_19/depth.pth'#1in
#    depth: '/home/roit/models/DeepSfM/kitti/0323_2159/models/weights_19/depth.pth'#3din
    #    depth: '/home/roit/models/monodepth2_official/mono_640x192/depth.pth'
    #pose: null
    posecnn: null
  device: 'cuda'
  optimizer_path: null
metric_mode: "mean"
dataset:
  type: 'kitti'
  path: '/home/roit/datasets/kitti'
  split:
    path: '/home/roit/datasets/splits/kitti/eigen_zhou_std'
    train_file: 'train.txt'
    val_file: 'val.txt'
    test_file: 'wo_test.txt'
  num_workers: 16
  batch_size: 16
  to_height: 192 #same with feed height
  to_width: 640
  full_width: 1242
  full_height: 375

feed_width: 640  #"'width' must be a multiple of 32"
feed_height: 192 #"'height' must be a multiple of 32"

cuda: True
device: 'cuda'

min_depth: 0.1
max_depth: 80.0