model:
  encoder_mode: "3din" #[encoder,depth,posecnn]
  load_paths:
    encoder: '/home/roit/models/DeepSfM/kitti/0501_0120/models/weights_9/depth_encoder.pth'
    depth: '/home/roit/models/DeepSfM/kitti/0501_0120/models/weights_9/depth.pth'
  device: 'cuda'
  scales: [0,1,2,3]
  optimizer_path: null
metric_mode: "mean"
dataset:
  type: 'kitti'
  path: '/home/roit/datasets/kitti'
  split:
    path: '/home/roit/datasets/splits/kitti/eigen_zhou_std'
    train_file: 'train.txt'
    val_file: 'val.txt'
    test_file: 'test.txt'
  num_workers: 12
  batch_size: 12
  to_height: 192 #same with feed height
  to_width: 640
  full_width: 1242
  full_height: 375

feed_width: 640  #"'width' must be a multiple of 32"
feed_height: 192 #"'height' must be a multiple of 32"

scales: [0,1,2,3]
cuda: True
device: 'cuda'

frame_sides: [-1,0,1]

min_depth: 0.1
max_depth: 80.0