model:
  mode: 0
  load_paths:
    encoder: null #'/home/roit/models/torchvision/official/resnet18-5c106cde.pth'
    depth: null
    #pose_encoder: null #'/home/roit/models/torchvision/official/resnet18-5c106cde.pth'
    #pose: null
    posecnn: null
  device: 'cuda'
  scales: [0,1,2,3]
  lr: 0.0001
  scheduler_step_size: 15
  optimizer_path: null


dataset:
  type: 'kitti'
  path: '/home/roit/datasets/kitti'
  split:
    path: '/home/roit/datasets/splits/eigen_zhou'
    train_file: 'train_files.txt'
    val_file: 'val_files.txt'
  num_workers: 12
  batch_size: 8
  to_height: 192 #same with feed height
  to_width: 640
  full_width: 1242
  full_height: 375

feed_width: 640  #"'width' must be a multiple of 32"
feed_height: 192 #"'height' must be a multiple of 32"

scales: [0,1,2,3]
disparity_smoothness: 0.1 #set manual
cuda: True
device: 'cuda'
epoch: 20

frame_sides: [-1,0,1]

yaml_file: /home/roit/aws/aprojects/DeepSfMLearner/opts/kitti.yaml
log_dir: '/home/roit/models/DeepSfM/kitti'
tb_log_frequency: 12
weights_save_frequency: 5
min_depth: 0.1
max_depth: 80.0
