model:
  framework: 'ind' #shared,ind,spv,rebuild
  mode: ['1in','default','3din','fin-2out'] #[encoder,depth,posecnn]
  load_paths:
#    depth_encoder: '/home/roit/models/torchvision/official/resnet18-5c106cde.pth'
#    pose_encoder: '/home/roit/models/torchvision/official/resnet18-5c106cde.pth'
#    depth_encoder: '/home/roit/models/DeepSfM/tmp/0317_0246/models/weights_29/encoder.pth'
#    pose_encoder: '/home/roit/models/DeepSfM/tmp/0317_0246/models/weights_29/encoder.pth'
    depth_encoder: null
    pose_encoder: null
  #    depth: null
#    pose: null
#    posecnn: null
  device: 'cuda'
  scales: [0,1,2,3]
  lr: 0.0001
  scheduler_step_size: 6
  optimizer_path: null

dataset:
  type: 'mc'
  path: '/home/roit/datasets/mcv5'
  split:
    path: '/home/roit/datasets/splits/mc/mcv5-sildurs-e-2k-12345'
    train_file: 'train.txt'
    val_file: 'val.txt'
  num_workers: 12
  batch_size: 8
  to_height: 288 #same with feed height
  to_width: 384
  full_width: 1024
  full_height: 768


scales: [0,1,2,3]
disparity_smoothness: 0.1 #set manual
cuda: True
device: 'cuda'

frame_sides: [-1,0,1]

yaml_file: /home/roit/aws/aprojects/DeepSfMLearner/opts/mc.yaml
log_dir: '/home/roit/models/DeepSfM/mc'
tb_log_frequency: 12
epoch: 10
model_first_save: 6
weights_save_frequency: 1
min_depth: 0.1
max_depth: 576.0