model:
  mode: ['1in','3din'] #[encoder,depth,posecnn]
  framework: 'sfmlearner' #rebuild #sfmlearner
  load_paths:
    encoder: '/home/roit/models/torchvision/official/resnet18-5c106cde.pth'
    depth: null
    #pose: null
    posecnn: null
  device: 'cuda'
  scales: [0,1,2,3]
  lr: 0.0001
  scheduler_step_size: 25
  optimizer_path: null

dataset:
  type: 'mc'
  path: '/home/roit/datasets/mcv21'
  split:
    path: '/home/roit/datasets/splits/mc/mcv21-sildurs-e-6k-12345'
    train_file: 'train.txt'
    val_file: 'val.txt'
  num_workers: 12
  batch_size: 8
  to_height: 288 #same with feed height
  to_width: 384
  full_width: 1024
  full_height: 768

feed_width: 384  #"'width' must be a multiple of 32"
feed_height: 288 #"'height' must be a multiple of 32"

scales: [0,1,2,3]
disparity_smoothness: 0.1 #set manual
cuda: True
device: 'cuda'

frame_sides: [-1,0,1]

yaml_file: /home/roit/aws/aprojects/DeepSfMLearner/opts/mc.yaml
log_dir: '/home/roit/models/DeepSfM/mc'
tb_log_frequency: 12
epoch: 30
model_first_save: 25
weights_save_frequency: 1
min_depth: 0.1
max_depth: 576.0