model:
  framework: 'ind' #shared,ind,spv,rebuild
  mode: ['1in','default','3din','fin-2out'] #[encoder,depth,posecnn]
  load_paths:
    depth_encoder: '/home/roit/bluep2/models/DeepSfM/mc_libs/0507_1431/models/weights_14/depth_encoder.pth'
  device: 'cuda'
  scales: [0,1,2,3]
  lr: 0.0001
  scheduler_step_size: 6
  optimizer_path: null

dataset:
  type: 'mc'
  path: '/home/roit/datasets/mnv0'
  split:
    path: '/home/roit/datasets/splits/mc/mnv0-all'
    train_file: 'train.txt'
    val_file: 'val.txt'
  num_workers: 12
  batch_size: 8
  to_height: 288 #same with feed height
  to_width: 384
  full_width: 1024
  full_height: 768


scales: [0,1,2,3]
disparity_smoothness: 0.1 #set manual
cuda: True
device: 'cuda'

frame_sides: [-1,0,1]

yaml_file: /home/roit/aws/aprojects/DeepSfMLearner/opts/mc.yaml
log_dir: '/home/roit/models/DeepSfM/mc'
tb_log_frequency: 12
epoch: 15
model_first_save: 10
weights_save_frequency: 1
min_depth: 0.1
max_depth: 576.0