model:
  encoder_mode: "3din" #[encoder,depth,posecnn]
  load_paths:
    encoder: '/home/roit/models/DeepSfM/mc/3d-mono/0525_1311/models/weights_14/depth_encoder.pth'
 #    encoder: '/home/roit/bluep2/models/DeepSfM/gnz-kitti/mono/0427_2137/models/weights_9/depth_encoder.pth'
#    encoder: '/home/roit/bluep2/models/DeepSfM/fpv-gnz/fpv_dt/0517_0558/models/weights_9/depth_encoder.pth'
#    depth: '/home/roit/bluep2/models/DeepSfM/fpv-gnz/fpv_dt/0517_0558/models/weights_9/depth.pth'
    depth: '/home/roit/models/DeepSfM/mc/3d-mono/0525_1311/models/weights_14/depth.pth'

  device: 'cuda'
  scales: [0,1,2,3]
  optimizer_path: null
metric_mode: "mean"
dataset:
  type: 'mc'
  path: '/home/roit/datasets/mcv5'
  split:
    path: '/home/roit/datasets/splits/mc/mcv5-sildurs(e)-6k-12345'
    train_file: 'train.txt'
    val_file: 'val.txt'
    test_file: 'test.txt'
  num_workers: 12
  batch_size: 12
  to_height: 288 #same with feed height
  to_width: 384
  full_width: 1024
  full_height: 768

feed_width: 384  #"'width' must be a multiple of 32"
feed_height: 288 #"'height' must be a multiple of 32"

scales: [0,1,2,3]
cuda: True
device: 'cuda'

frame_sides: [-3,0,3]

min_depth: 0.1
max_depth: 576.0