model:
  mode: 0 #[encoder,depth,posecnn]
  load_paths:
    encoder: '/home/roit/models/DeepSfM/mc/02192005/models/weights_29/encoder.pth'
    depth: '/home/roit/models/DeepSfM/mc/02192005/models/weights_29/depth.pth'
    #pose: null
    posecnn: null
  device: 'cuda'
  scales: [0,1,2,3]
  optimizer_path: null

dataset:
  type: 'mc'
  path: '/home/roit/datasets/mcv4'
  split:
    path: '/home/roit/datasets/splits/mc/mcv4-sildurs-h-2k-12345'
    train_file: 'train.txt'
    val_file: 'val.txt'
    test_file: 'test.txt'
  num_workers: 12
  batch_size: 16
  to_height: 288 #same with feed height
  to_width: 384
  full_width: 1024
  full_height: 768

feed_width: 384  #"'width' must be a multiple of 32"
feed_height: 288 #"'height' must be a multiple of 32"

scales: [0,1,2,3]
cuda: True
device: 'cuda'

frame_sides: [-1,0,1]

yaml_file: /home/roit/aws/aprojects/DeepSfMLearner/opts/mc.yaml
log_dir: '/home/roit/models/DeepSfM/mc'
tb_log_frequency: 12
weights_save_frequency: 5
min_depth: 0.1
max_depth: 576.0