model:
  encoder_mode: "3din" #[encoder,depth,posecnn]
  load_paths:
    encoder: '/home/roit/models/DeepSfM/mc_lights/0426_0428/models/weights_9/encoder.pth'
    depth: '/home/roit/models/DeepSfM/mc_lights/0426_0428/models/weights_9/depth.pth'
  device: 'cuda'
  scales: [0,1,2,3]
  optimizer_path: null
metric_mode: "mean"
dataset:
  type: 'mc'
  path: '/home/roit/datasets/mcv5'
  split:
    path: '/home/roit/datasets/splits/mc/mcv5-sildurs-e-10k-12345-s'
    train_file: 'train.txt'
    val_file: 'val.txt'
    test_file: 'test.txt'
  num_workers: 12
  batch_size: 12
  to_height: 288 #same with feed height
  to_width: 384
  full_width: 1024
  full_height: 768

feed_width: 384  #"'width' must be a multiple of 32"
feed_height: 288 #"'height' must be a multiple of 32"

scales: [0,1,2,3]
cuda: True
device: 'cuda'

frame_sides: [-1,0,1]

min_depth: 0.1
max_depth: 576.0