model:
  init_weight_path: '/home/roit/models/monodepth2_official/mono_640x192'
  load_models: ['depth','encoder','pose','pose_encoder']
  device: 'cuda'
  scales: [0,1,2,3]
  lr: 0.001
  scheduler_step_size: 15

dataset:
  type: 'kitti'
  path: '/home/roit/datasets/kitti'
  split:
    path: '/home/roit/datasets/splits/custom_lite'
    train_file: 'train_files.txt'
    val_file: 'val_files.txt'
  num_workers: 12
  batch_size: 8
  to_height: 192 #same with feed height
  to_width: 640
  full_width: 1242
  full_height: 375

feed_width: 640  #"'width' must be a multiple of 32"
feed_height: 192 #"'height' must be a multiple of 32"

scales: [0,1,2,3]
disparity_smoothness: 0.1 #set manual
lr: 0.001
cuda: True
device: 'cuda'
epoch: 20

frame_idxs: [-1,0,1]


log_dir: '/home/roit/models/monodepth2/kitti'
tb_log_frequency: 12
weights_save_frequency: 5
min_depth: 0.1
max_depth: 80.0




