model:
  init_weight_path: '/home/roit/models/monodepth2_official/mono_640x192'
  feed_width: 640
  feed_height: 192
  full_width: 1242
  full_height: 375
  frame_ids: [-1,0,1]
  scales: [0,1,2,3]
  disparity_smoothness: 0.1
  lr: 0.001


settings:
  epoch: 20
  batch_size: 8
  weights_save_frequency: 1
  log_dir: '/home/roit/models/monodepth2/kitti'
  tb_log_frequency: 12
  min_depth: 0.1
  max_depth: 80.0
  cuda: True


dataset:
  type: 'KITTI'
  path: '/home/roit/datasets/kitti'
  split:
    path: '/home/roit/datasets/splits/eigen_zhou_std'
    train_file: 'train_files.txt'
    val_files: 'val_files.txt'
  num_workers: 12
