model:
  framework: 'shared' #shared,ind,spv,rebuild
  mode: ['3din','default','3din','fin-2out'] #[encoder,depth,posecnn]
  load_paths:
    depth_encoder: '/home/roit/models/torchvision/official/resnet18-5c106cde.pth'
    pose_encoder: '/home/roit/models/torchvision/official/resnet18-5c106cde.pth'
#    depth_encoder: '/home/roit/models/DeepSfM/tmp/0317_0246/models/weights_29/encoder.pth'
#    pose_encoder: '/home/roit/models/DeepSfM/tmp/0317_0246/models/weights_29/encoder.pth'
#    depth_encoder: null
#    pose_encoder: null
  #    depth: null
#    pose: null
#    posecnn: null
  device: 'cuda'
  scales: [0,1,2,3]
  lr: 0.0001
  scheduler_step_size: 6
  optimizer_path: null

dataset:
  type: 'custom_mono'
  path: '/home/roit/datasets/VSD'
  split:
    path: '/home/roit/datasets/splits/vsd/vsd10k'
    train_file: 'train.txt'
    val_file: 'val.txt'
  num_workers: 12
  batch_size: 8
  to_height: 256 #same with feed height
  to_width: 384
  full_width: null
  full_height: null

feed_width: 384  #"'width' must be a multiple of 32"
feed_height: 256 #"'height' must be a multiple of 32"

scales: [0,1,2,3]
disparity_smoothness: 0.1 #set manual
cuda: True
device: 'cuda'

frame_sides: [-1,0,1]

yaml_file: /home/roit/aws/aprojects/DeepSfMLearner/opts/vsd.yaml
log_dir: '/home/roit/models/DeepSfM/vsd'
tb_log_frequency: 12
epoch: 10
model_first_save: 6
weights_save_frequency: 1
min_depth: 0.1
max_depth: 100.0