model:
  framework: 'ind' #shared,ind,spv,rebuild
  mode: ['1in','default','3din','fin-2out'] #[encoder,depth,posecnn]
  load_paths:
    depth_encoder: null
    pose_encoder: null
  device: 'cuda'
  scales: [0,1,2,3]
  lr: 0.0001
  scheduler_step_size: 2
  optimizer_path: null

dataset:
  type: 'custom_mono'
  path: '/home/roit/970evop6/datasets/fpv_downtown'
  split:
    path: '/home/roit/datasets/splits/fpv_downtowns'
    train_file: 'train.txt'
    val_file: 'val.txt'
  num_workers: 12
  batch_size: 36
  to_height: 128 #same with feed height
  to_width: 192
  full_width: null
  full_height: null

feed_width: 384  #"'width' must be a multiple of 32"
feed_height: 256 #"'height' must be a multiple of 32"

scales: [0,1,2,3]
disparity_smoothness: 0.1 #set manual
cuda: True
device: 'cuda'

frame_sides: [-2,0,2]

yaml_file: /home/roit/aws/aprojects/DeepSfMLearner/opts/fpv.yaml
log_dir: '/home/roit/models/DeepSfM/fpv'
tb_log_frequency: 12
epoch: 8
model_first_save: 5
weights_save_frequency: 1
min_depth: 0.1
max_depth: 100.0