model:
  paradigm: 'ind' #shared,ind,spv,rebuild
  components: ['1in','default','3din','fin-2out'] #[encoder,depth,posecnn]
  load_paths:
    depth_encoder: '/home/roit/st_ext4/models/DeepSfM/gnz-kitti/mono/0508_1754/models/weights_9/depth_encoder.pth'
    depth: '/home/roit/st_ext4/models/DeepSfM/gnz-kitti/mono/0508_1754/models/weights_9/depth.pth'
#    depth_encoder: '/home/roit/models/monodepth2_official/mono_640x192/encoder.pth'
#    depth: '/home/roit/models/monodepth2_official/mono_640x192/depth.pth'
  lr: 0.0001
  scheduler_step_size: 6
  optimizer_path: null

dataset:
  type: 'kitti'
  path: '/home/roit/st_ext4/datasets/kitti'
  split:
    path: '/home/roit/datasets/splits/kitti/eigen_zhou_std'
    train_file: 'train.txt'
    val_file: 'val.txt'
    test_file: 'test.txt'
  num_workers: 2
  batch_size: 1
  full_width: 1242
  full_height: 375



feed_height: 192 #same with feed height
feed_width: 640

scales: [0,1,2,3]
disparity_smoothness: 0.1 #set manual

#device: ["cuda:0","cuda:1"]
device: ["cuda:0"]

# device: "cuda:1"

frame_sides: [-1,0,1]

log_dir: '/home/roit/models/DeepSfM/kitti'
tb_log_frequency: 12
tb_log_setting: {'1000':10,'10000':100,'100000':100}
epoch: 15
model_first_save: 10
weights_save_frequency: 1
min_depth: 0.1
max_depth: 80.0



