model:
  framework: 'shared' #shared,ind,spv,rebuild
  mode: ['3din','default','3din','fin-2out'] #[encoder,depth,posecnn]
  load_paths:
    encoder: '/home/roit/models/torchvision/official/resnet18-5c106cde.pth'
#    pose_encoder: '/home/roit/models/DeepSfM/mc/0507_1431/models/weights_14/pose_encoder.pth'
#    depth_encoder: '/home/roit/models/DeepSfM/tmp/0317_0246/models/weights_29/encoder.pth'
#    pose_encoder: '/home/roit/models/DeepSfM/tmp/0317_0246/models/weights_29/encoder.pth'
#    depth_encoder: null
#    pose_encoder: null
  #    depth: null
#    pose: null
#    posecnn: null
  device: 'cuda'
  scales: [0,1,2,3]
  lr: 0.0001
  scheduler_step_size: 6
  optimizer_path: null

dataset:
  type: 'kitti'
  path: '/home/roit/datasets/kitti'
  split:
    path: '/home/roit/datasets/splits/kitti/eigen_zhou_std'
    train_file: 'train.txt'
    val_file: 'val.txt'
  num_workers: 12
  batch_size: 8
  to_height: 192 #same with feed height
  to_width: 640
  full_width: 1242
  full_height: 375


scales: [0,1,2,3]
disparity_smoothness: 0.1 #set manual
cuda: True
device: 'cuda'

frame_sides: [-1,0,1]

yaml_file: /home/roit/aws/aprojects/DeepSfMLearner/opts/kitti.yaml
log_dir: '/home/roit/models/DeepSfM/kitti'
tb_log_frequency: 12
epoch: 10
model_first_save: 6
weights_save_frequency: 1
min_depth: 0.1
max_depth: 80.0